### ISSUE TITLE
turbo colormap not included

### ISSUE THREAD

**Issue by etrautmann** [djoshea/neuropixel-utils#13]
I get the following error trying to plot cluster waveforms - looks like a dependency on this function:
https://www.mathworks.com/matlabcentral/fileexchange/74662-turbo.

Might consider changing to a different default colormap or including turbo in this repo. 

Unrecognized function or variable 'turbomap'.

Error in Neuropixel.KilosortMetrics/plotClusterWaveformAtCentroid (line 2206)
                    colormap = turbomap(numel(clusterInds));

**Comment by djoshea** [comment]
Ah, oops. If you're using R2020b, you can just swap in `turbo()`.
https://www.mathworks.com/help/matlab/ref/turbo.html

**Comment by etrautmann** [comment]
Yep, thanks!
