### ISSUE TITLE
Outdated function reference?

### ISSUE THREAD

**Issue by yaxigeigei** [djoshea/neuropixel-utils#16]
https://github.com/djoshea/neuropixel-utils/blob/ae56e18d862acf46f1f57915ffa87ae1e8769cfa/%2BNeuropixel/KilosortMetrics.m#L1133

This seems like an outdated function reference, and the new one is probably "Neuropixel.Utils.setLineOpacity"?

(Thank you for this awesome toolbox! I have written my own, also oop, toolkit for SpikeGLX and Kilosort1/2, but once seeing this beautifully designed and professionally written package I immediately threw mine away haha!!)

**Comment by djoshea** [comment]
Hi Duo, thanks for finding this, and thanks for your kind comments. I'd just forgotten to copy this function over from my other repo (https://github.com/djoshea/trial-data).

Hopefully this fixes it!
Dan
