### ISSUE TITLE
Error while loading binaries from SpikeGLX (Release v.20190327) - port numbers on imec PXI card

### ISSUE THREAD

**Issue by PierreLeMerre** [djoshea/neuropixel-utils#2]
A small error appears while loading "imec.ap.bin". This could be due to the fact that the latest release of SpikeGLX change the file name to "imec**X**.ap.bin" where **X** is the probe port number on the imec PXI card.

**Comment by djoshea** [comment]
I believe this is now fixed. Let me know if anyone is still having trouble with it.
