### ISSUE TITLE
Issue with concatenating LF

### ISSUE THREAD

**Issue by peterfschade** [djoshea/neuropixel-utils#3]
An error was returned when concatenating files LF but not AP data using Neuropixel.ImecDataset.writeConcatenatedFileMatchGains. There was no field of 'badChannels' in the LFmeta.

I changed the union of badChannels with the 'if p.Results.writeLF ...' statement to the following and it works for what I have been doing but there is probably a more logical place to define the meta data. 

 % compute union of badChannels
                for iM = 2:numel(imecList)
                    if ~isfield(meta, 'badChannels')
                        meta.badChannels = [];
                    else
                        meta.badChannels = union(meta.badChannels, imecList{iM}.badChannels);
                    end
                end
 
I define the badChannels after concatenating all my Imec datasets. Should I be populating that field prior to concatenating?

**Comment by djoshea** [comment]
Hi Peter, sorry, somehow I didn't see the notification email for this. If there's any chance you're still having this issue, would you mind trying to run the concatenation pipeline using the latest commit in the `markSplitOnly` branch? I've made a bunch of changes there that I've used locally, including dealing with just LF datasets, but haven't merged them into master yet. 

If this is no longer salient / worth your time to debug, no worries, I'll get around to merging it back into master eventually.

Thanks, and sorry for the very delayed response.
Dan

**Comment by peterfschade** [comment]
I had forgotten about this. I was fine with the above for what I need for my analyses.
